//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Otherlink { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Location1 { get; set; }
        public string Location2 { get; set; }
        public byte[] Logo { get; set; }
        public bool Individual { get; set; }
        public bool Dealer { get; set; }
        public string DealerName { get; set; }
    }
}
